bazel_dep(name = "rules_cc", version = "0.0.17")

# You must add rules_python because the newer extractor commit relies on it
bazel_dep(name = "rules_python", version = "0.31.0")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # This commit hash is from a pending PR that fixes Bazel 8+ compatibility
    commit = "7fe1eab26d2b8eeb5e1c6a2f38bddb001e3f9696",
)
