load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name="salt_lib",
    srcs=["defaults.cc", "file-handler.cc", "options-handler.cc"],
    hdrs=["defaults.h", "file-handler.h", "options-handler.h"],
    visibility=["//main:__pkg__"],
)
